<%@ Page Title="" Language="C#" MasterPageFile="~/page.master" AutoEventWireup="true" CodeFile="check_emp.aspx.cs" Inherits="page_check_emp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
      <link href="../css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="../css/style.css">

        <center>
            <k1>ตรวจสอบข้อมูลบุคคลากร</k1></center>

    
    <table class="table table-condensed">
      
  <tr class="active">

      <td class="active" style="width: 230px">
          ชื่อบุคคลากร</td>
        <td class="active" style="width: 342px">
            <asp:TextBox ID="txtstaff" class="form-control"  runat="server" Height="29px" Width="514px"></asp:TextBox>
      </td>
         <td class="active" colspan="3">
             <asp:Button ID="btnsurch" runat="server" class="btn btn-default"  Text="ค้นหา" Height="45px" Width="168px" OnClick="btnsurch_Click" />
      </td>
  </tr>
          <tr class="active">
     <!--   <td class="active" style="width: 230px" colspan="3">
       <div id="menu">
  <ul>
    <li><a href="../page/patientregister.aspx">กรอกประวัติคนไ</a>ช</li>


   
  </ul>
         
</div> 
      </td>-->
                    <td class="active" style="width: 230px" colspan="3">
                        ตารางข้อมูลบุคคลากร
                        <center>   <asp:GridView ID="GridView1" runat="server" CellPadding="3" GridLines="Vertical" Height="245px" Width="861px" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Employees_id">
        <AlternatingRowStyle BackColor="#DCDCDC" />
              <Columns>
                  <asp:BoundField DataField="Employees_id" HeaderText="รหัสพนักงาน" InsertVisible="False" ReadOnly="True" SortExpression="Employees_id" />
                  <asp:BoundField DataField="username" HeaderText="username" SortExpression="username" />
                  <asp:BoundField DataField="password" HeaderText="password" SortExpression="password" />
                  <asp:BoundField DataField="name" HeaderText="ชื่อ" SortExpression="name" />
                  <asp:BoundField DataField="Job_position" HeaderText="ตำแหน่ง" SortExpression="Job_position" />
                  <asp:BoundField DataField="address" HeaderText="ที่อยู่" SortExpression="address" />
                    <asp:BoundField DataField="Tel" HeaderText="เบอร์โทร" SortExpression="Tel" />
            </Columns>
        
        <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
        <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
        <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />

        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#0000A9" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#000065" />
    </asp:GridView>

      <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Connectionstring %>" SelectCommand="SELECT [username], [password], [name], [Job_position], [address], [Tel], [Employees_id] FROM [Employees]" UpdateCommand="UPDATE [Employees] SET [username] = @username, [password] = @password, [name] = @name, [Job_position] = @Job_position, [address] = @address, [Tel] = @Tel WHERE [Employees_id] = @Employees_id" DeleteCommand="DELETE FROM [Employees] WHERE [Employees_id] = @Employees_id" InsertCommand="INSERT INTO [Employees] ([username], [password], [name], [Job_position], [address], [Tel]) VALUES (@username, @password, @name, @Job_position, @address, @Tel)">
          <DeleteParameters>
              <asp:Parameter Name="Employees_id" Type="Int32" />
          </DeleteParameters>
          <InsertParameters>
              <asp:Parameter Name="username" Type="String" />
              <asp:Parameter Name="password" Type="String" />
              <asp:Parameter Name="name" Type="String" />
              <asp:Parameter Name="Job_position" Type="String" />
              <asp:Parameter Name="address" Type="String" />
              <asp:Parameter Name="Tel" Type="String" />
          </InsertParameters>
          <UpdateParameters>
              <asp:Parameter Name="username" Type="String" />
              <asp:Parameter Name="password" Type="String" />
              <asp:Parameter Name="name" Type="String" />
              <asp:Parameter Name="Job_position" Type="String" />
              <asp:Parameter Name="address" Type="String" />
              <asp:Parameter Name="Tel" Type="String" />
              <asp:Parameter Name="Employees_id" Type="Int32" />
          </UpdateParameters>
                            </asp:SqlDataSource></center>
        
      </td>
     
  </tr>

         <tr class="active">

      <td class="active" style="width: 230px" colspan="3">
          <asp:LinkButton ID="LinkButton1" runat="server" OnClick="LinkButton1_Click1">กลับมาหน้าแรก</asp:LinkButton>
      </td>
     
  </tr>
    </table>
    
   
</asp:Content>

